baseurl = "http://alpha.avant.org/"
languageCode = "en-us"
title = "avant.org"
googleAnalytics = "UA-46800316-1"
watch = true
FootnoteReturnLinkContents = "↥"
builddrafts = true

all = ["project", "artifact", "event", "gallery"]

[blackfriday]
	hrefTargetBlank = true

[taxonomies]
	tag = "tag"
	thread = "thread"
	author = "author"

[params]
	name = "Your name"
	description = "A project space for the internet and elsewhere."

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

	[params.menu]
		# Menu items
		title = "avant.org"
		bio = "A project space for the internet and elsewhere."

		# Enable Google search
		search_enabled = false
		search = "Search"

	[params.authors]
		[params.authors.taeyoon.choi]
			name          = "Taeyoon Choi"
			thumbnail     = "http://objects.avant.org/author_photos/taeyoon_choi.jpeg"
			bio           = "taeyoon's bio"
			email         = "test@gmail.com"
		[params.authors.taeyoon.choi.social]
			twitter       = "tchoi8"

		[params.authors.sam.silver]
			name          = "Sam Silver"
			thumbnail     = "http://objects.avant.org/author_photos/sam_silver.jpeg"
			bio           = "ss's bio"
			email         = "test2@gmail.com"
		[params.authors.sam.silver.social]
			twitter       = "_samsilver"