baseurl = "http://avant.org/"
languageCode = "en-us"
title = "Avant.org"
googleAnalytics = "UA-46800316-1"
watch = true
FootnoteReturnLinkContents = "↥"
builddrafts = true

[blackfriday]
	hrefTargetBlank = true

[taxonomies]
	tag = "tag"
	thread = "thread"
	author = "author"

[params]
	name = "Avant.org"
	description = "A project space for the internet and elsewhere."
	indextypes = ["project", "artifact", "event", "gallery"]

	# links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "404"
	pageNotFoundSubtitle = "Page not found."

	[params.menu]
		# Menu items
		title = "Avant.org"
		bio = "A project space for the internet and elsewhere."
