baseurl = "http://alpha.avant.org/"
languageCode = "en-us"
title = "Avant.org"
googleAnalytics = "UA-46800316-1"
watch = true
FootnoteReturnLinkContents = "↥"
builddrafts = true
pygmentsuseclasses = true
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

[blackfriday]
	hrefTargetBlank = true

[taxonomies]
	tag = "tag"
	thread = "thread"
	author = "author"
	editor = "editor"

[params]
	name = "Avant.org"
	description = "A distributed project space for research and practice."

	# links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "404"
	pageNotFoundSubtitle = "Page not found."
